# config/schema/commerce_quickpay.schema.yml
commerce_payment.commerce_payment_gateway.plugin.quickpay_pagseguro_checkout:
  type: commerce_payment_gateway_configuration
  mapping:
    email:
      type: string
      label: 'Email'
    token:
      type: string
      label: 'Token'
    token_sandbox:
      type: string
      label: 'Token Sandbox'
    email_buyer_sandbox:
      type: string
      label: 'Buyer Email'
    endpoint:
      type: string
      label: 'PagSeguro URL'
    endpoint_sandbox:
      type: string
      label: 'PagSeguro URL'